[config]
default_to_workspace = false

[tasks.run-vm]
script = ['''
  set -euo pipefail
  TARGET_BASE="$(cargo metadata --format-version 1 --no-deps | jq -r '.target_directory')"
  MUSL_TARGET="x86_64-unknown-linux-musl"
  cargo build --release --target "${MUSL_TARGET}" -p netsim --bin netsim --example transfer
  cargo run -p netsim-vm -- run --netsim-version "path:${TARGET_BASE}/${MUSL_TARGET}/release/netsim" ${@}
  ''']

[tasks.test-vm]
script = ['''
  set -euo pipefail
  cargo run -p netsim-vm -- test --target "x86_64-unknown-linux-musl" ${@}
  ''']

[tasks.format]
workspace = false
command = "cargo"
args = [
     "fmt",
     "--all",
     "--",
     "--config",
     "unstable_features=true",
     "--config",
     "imports_granularity=Crate,group_imports=StdExternalCrate,reorder_imports=true,format_code_in_doc_comments=true",
]

[tasks.format-check]
workspace = false
command = "cargo"
args = [
     "fmt",
     "--all",
     "--check",
     "--",
     "--config",
     "unstable_features=true",
     "--config",
     "imports_granularity=Crate,group_imports=StdExternalCrate,reorder_imports=true,format_code_in_doc_comments=true",
]
