[config]
# default_task = "start"

[env]
VM_NAME = "netsim-vm"
MUSL_TARGET = "x86_64-unknown-linux-musl"

[tasks.setup-vm]
script = ["""
  set -euo pipefail
  TARGET_BASE="$(cargo metadata --format-version 1 --no-deps | jq -r '.target_directory')"
  mkdir -p "${TARGET_BASE}"
  NAME="${VM_NAME}" ./vm-up.sh "${TARGET_BASE}"
  """]

[tasks.target-dir]
script = ['''
  set -euo pipefail
  if [ -n "${RUST_TARGET:-}" ]; then
    target="${RUST_TARGET}"
  else
    target="$(rustc -vV | awk '/^host:/{print $2}')"
  fi
  base="$(cargo metadata --format-version 1 --no-deps | jq -r '.target_directory')"
  echo "${base}/${target}"
  ''']

[tasks.setcap]
command = "./setcap.sh"

[tasks.build-vm]
command = "cargo"
args = ["build", "--release", "--target", "${MUSL_TARGET}"]

[tasks.build-test-vm]
command = "cargo"
args = ["test", "--no-run", "--target", "${MUSL_TARGET}"]

[tasks.run-local]
dependencies = ["setcap"]
command = "cargo"
args = ["run"]

[tasks.test-local]
dependencies = ["setcap"]
command = "cargo"
args = ["test"]

[tasks.run-vm]
dependencies = ["setup-vm", "build-vm", "prepare-vm"]
script = ['''
  limactl shell --workdir / ${VM_NAME} sudo /target/${MUSL_TARGET}/release/${CARGO_MAKE_CRATE_NAME} ${ARGS}
  ''']

[tasks.test-vm]
dependencies = ["setup-vm", "build-test-vm", "prepare-vm"]
script = ['''
  limactl shell --workdir / ${VM_NAME} sudo sh -c 'for t in /target/${MUSL_TARGET}/debug/deps/${CARGO_MAKE_CRATE_NAME}-*; do case "$t" in *.d) continue ;; esac; if [ -x "$t" ]; then "$t"; fi; done'
  ''']

[tasks.prepare-vm]
dependencies = ["setup-vm"]
script = ['''
  limactl shell --workdir / ${VM_NAME} sudo sysctl -w net.ipv4.ip_forward=1
  ''']

[tasks.shutdown]
script = ['''
  echo "Shutting down Lima VM..."
  limactl stop ${VM_NAME}
  ''']

[tasks.start]
dependencies = ["setup-vm", "run-vm"]
